AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  event-driven-order-processing

  Sample SAM Template for event-driven-order-processing

Globals:
  Function:
    Timeout: 3  # Keep SQS VisibilityTimeout >= ~6x this (set to 30s below)

Resources:
  # --- Queues ---
  OrdersQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: orders-dlq

  OrdersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: orders-queue
      # VisibilityTimeout should comfortably exceed Lambda timeout to avoid duplicate processing
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrdersQueueDLQ.Arn
        maxReceiveCount: 5

  # --- Lambda ---
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      # Grant the Lambda permission to poll & delete messages from this SQS queue
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt OrdersQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrdersQueue.Arn
            # Tune these for throughput/latency tradeoffs
            BatchSize: 10                         # up to 10 for standard queues
            MaximumBatchingWindowInSeconds: 2     # small delay to form batches
            Enabled: true

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  OrdersQueueUrl:
    Description: "Orders SQS Queue URL"
    Value: !Ref OrdersQueue
  OrdersQueueArn:
    Description: "Orders SQS Queue ARN"
    Value: !GetAtt OrdersQueue.Arn
  OrdersDLQUrl:
    Description: "Orders DLQ URL"
    Value: !Ref OrdersQueueDLQ
  OrdersDLQArn:
    Description: "Orders DLQ ARN"
    Value: !GetAtt OrdersQueueDLQ.Arn
